// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3R2yULThM-fXltP5vhPba73pgO3fA31A',
    appId: '1:279472999275:web:4cce9b0a59069cab89da2e',
    messagingSenderId: '279472999275',
    projectId: 'filmfinder-895d0',
    authDomain: 'filmfinder-895d0.firebaseapp.com',
    storageBucket: 'filmfinder-895d0.appspot.com',
    measurementId: 'G-4306D1VFDF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5MAq2j7VMOTwXY7lAE8zumpbDwFUVYvw',
    appId: '1:279472999275:android:5e668312f7c751fb89da2e',
    messagingSenderId: '279472999275',
    projectId: 'filmfinder-895d0',
    storageBucket: 'filmfinder-895d0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBAEtsWdJMw9Ukc2Nb-jAGGpI1L_wKYKHs',
    appId: '1:279472999275:ios:6e2be0c75624f2b189da2e',
    messagingSenderId: '279472999275',
    projectId: 'filmfinder-895d0',
    storageBucket: 'filmfinder-895d0.appspot.com',
    iosBundleId: 'com.example.filmFinder',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBAEtsWdJMw9Ukc2Nb-jAGGpI1L_wKYKHs',
    appId: '1:279472999275:ios:6e2be0c75624f2b189da2e',
    messagingSenderId: '279472999275',
    projectId: 'filmfinder-895d0',
    storageBucket: 'filmfinder-895d0.appspot.com',
    iosBundleId: 'com.example.filmFinder',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA3R2yULThM-fXltP5vhPba73pgO3fA31A',
    appId: '1:279472999275:web:35ef267791c2620e89da2e',
    messagingSenderId: '279472999275',
    projectId: 'filmfinder-895d0',
    authDomain: 'filmfinder-895d0.firebaseapp.com',
    storageBucket: 'filmfinder-895d0.appspot.com',
    measurementId: 'G-T9K2XN9C6E',
  );

}